title: Abhishek Shah
email: contact@abhishek-shah.org
url: "https://abhishek-shah.org"
github_username: ashah2012
twitter_username: avishek_20

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
