# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: abhishek shah's blog
email: ashah201291@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog contains things that I learn everyday.
  Properly writing everything helps you remember
  them longer.


baseurl: "" # the subpath of your site, e.g. /blog
url: http://abhishek-shah.org
twitter_username: avishek_20
github_username:  ashah2012

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock



#google-analytics
google_analytics: UA-102588107-1
